### PR TITLE
Fix missing failure text in Capybara 2.9+

### PR DESCRIPTION
**Pull request by GUI**
If minitest-capybara is used with Capybara 2.9+ then failures for certain assertions (like assert_link), will throw this error, rather than reporting the failure:

```
NoMethodError: undefined method `failure_message' for Capybara::Helpers:Module
```

The reason is because the `Capybara::Helpers.failure_message` method was refactored and disappeared in 2.9: https://github.com/teamcapybara/capybara/pull/1748

As noted in the pull request, `Capybara::Helpers` module is technically marked private, so this fixes it by bringing the necessary methods into minitest-capybara's code base.

I believe this should also solve a potential issue with some of the `refute_*` helpers returning the incorrect failure message (back when this was working with Capybara < 2.9). Since `failure_message` was being called for both assertions and refutations, the message was presumably the same. This updates things to use a separate `negative_failure_message` for the refutations (so `refute_link` would report "expected not to find..." instead of "expected to find...").

### CODE REVIEW

**Comment by GUI** [comment]
It looks like the TravisCI failures are due to it installing Rack 2.0, which isn't compatible with older versions of Ruby (so the Ruby 2.2 and 2.1 tests are failing). But the tests are passing in Ruby 2.3.

Let me know if you'd like for me to try and fix this as part of this pull request, or if you'd prefer to handle that separately.

**Comment by CyborgMaster** [comment]
I was having the same error, and can confirm that this PR fixed it for me.  @GUI, I'm using your fork for now.

File: lib/capybara/assertions.rb [hunk 1]
```diff
@@ -290,5 +290,37 @@ def prepare_args(args)
         [page, *args]
       end
     end
+
+    module CapybaraFailureHelpers
+      def self.failure_message(description, options={})
+        String.new("expected to find #{description}") << count_message(options)
```
Comment (wojtekmach) [inline lib/capybara/assertions.rb]: I think this could be simply:

```ruby
"expected to find #{description}#{count_message(options)}"
```

WDYT?

File: lib/capybara/assertions.rb [hunk 2]
```diff
@@ -290,5 +290,37 @@ def prepare_args(args)
...
+        if count == 1
+          singular
+        else
+          plural
+        end
+      end
+
+      def self.count_message(options)
+        message = String.new()
+        if options[:count]
```
Comment (wojtekmach) [inline lib/capybara/assertions.rb]: since all of the branches are mutually exclusive, there's no need to mutate the `message` string. Could you rewrite to:

```ruby
def self.count_message(options)
  case
  when options[:count]
    " #{options[:count]} #{declension('time', 'times', options[:count])}"
  when ...
    ...
  end
end
```

**Comment by wojtekmach** [comment]
> Let me know if you'd like for me to try and fix this as part of this pull request, or if you'd prefer to handle that separately.

I'd appreciate that, I think we should continue to support ruby >= 2.0

**Comment by clthck** [comment]
When will this PR be merged followed by a new release?

**Comment by blowmage** [comment]
This PR will be merged when the code is altered to match the feedback given, and the review changed to approved.

**Comment by blowmage** [comment]
Will these changes work on Capybara versions < 2.9?

**Comment by NanoMeko** [comment]
this module seems to help display the correct messages until the changes are added to the gem

https://gist.github.com/Patru/6623747

**Comment by mltsy** [comment]
:+1: Maybe someone who's using this could fork from @GUI and submit a new PR with the requested changes (since he/she has moved on apparently)?

**Comment by wojtekmach** [comment]
Thank you! I've made the minor changes on master and released v0.9.0.
